"""description default value

Revision ID: 583ede9859a1
Revises: 789953bf9c87
Create Date: 2025-03-11 04:08:37.145617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583ede9859a1'
down_revision: Union[str, None] = '789953bf9c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('found_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lost_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lost_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('found_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
